[package]
name = "rocmsmi-wrapper-sys"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/sustainai-energy/amdsmi-wrapper/tree/main/rocmsmi-wrapper"

[package.metadata.cargo-machete]
ignored = ["bindgen", "libloading"]

[dependencies]
libloading = { version = "0.9" }

[build-dependencies]
bindgen = { version = "0.73" }
