[package]
name = "rocmsmi-wrapper"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Safe Rust wrapper for the ROCm SMI library"
repository = "https://github.com/sustainai-energy/amdsmi-wrapper/tree/main/rocmsmi-wrapper"

[dependencies]
libloading = { version = "0.9" }
rocmsmi-wrapper-sys = { path = "../rocmsmi-wrapper-sys", version = "0.1.0" }
thiserror = { version = "2.0" }
