[package]
name = "amdsmi-wrapper"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Safe Rust wrapper for the AMD System Management Interface (AMD SMI) library"
repository = "https://github.com/sustainai-energy/amdsmi-wrapper/tree/main/amdsmi-wrapper"

[dependencies]
amdsmi-wrapper-sys = { path = "../amdsmi-wrapper-sys", version = "0.1.0" }
libloading = { version = "0.9" }
thiserror = { version = "2.0" }
