name: machete
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  actions: write
env:
  CARGO_TERM_COLOR: always
jobs:
  machete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: Swatinem/rust-cache@v2
    - name: install cargo-outdated
      run: cargo install cargo-machete --locked
    - name: machete
      run: cargo machete --with-metadata
